// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdKX6O244rMfV2tLylELRLqbI6GBIAXE0',
    appId: '1:621582381813:android:9b0765ae43393d5fff4bbc',
    messagingSenderId: '621582381813',
    projectId: 'firebase-core-initialize',
    storageBucket: 'firebase-core-initialize.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN24ZfccONOq7wy60yCgxRUvkb3b2WOb8',
    appId: '1:621582381813:ios:57886cb5357dfe81ff4bbc',
    messagingSenderId: '621582381813',
    projectId: 'firebase-core-initialize',
    storageBucket: 'firebase-core-initialize.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCoreInitialize',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEiXMYQctb9tjxfCnkvLa3D6iPvWAbF00',
    appId: '1:621582381813:web:6c54d52c42519d18ff4bbc',
    messagingSenderId: '621582381813',
    projectId: 'firebase-core-initialize',
    authDomain: 'fir-core-initialize.firebaseapp.com',
    storageBucket: 'firebase-core-initialize.firebasestorage.app',
  );

}